### ISSUE TITLE
data display in the front page is not 3 columns grid

### ISSUE THREAD

**Issue by PhoebeYahengWu** [AnthonySugrim/Skill-Share#20]
<img width="948" alt="Capture" src="https://user-images.githubusercontent.com/52837649/81819320-2c5ab400-94fd-11ea-89f3-e94a9378199d.PNG">

**Comment by carolninganga** [comment]
the issue was resolved...:)
<img width="1249" alt="Screen Shot 2020-05-13 at 10 47 28 AM" src="https://user-images.githubusercontent.com/33443452/81827956-46998f80-9507-11ea-9f1e-188cb4a52558.png">
